language: python
python:
- '2.7'
- '3.7'
install:
- pip install pycodestyle
script:
- pycodestyle kivmob.py
deploy:
  skip_existing: true
  provider: pypi
  user: mstott6
  on:
    branch: master
  password:
    secure: ZOg6EL7msC7+AR9Zoptbxj+Mcu9dF9o5LFSRmv+LJ9TrJbgvrjHWLnybzcSsLV3n/6rrn2JBoVY0I3zFN1C9sWbbbxPZhAgd3QPyhoAg+ip+GLJLv9OAuSQAJ9U4RLa63kJJbW2sCrrypjuz3XDDpJcIWoa/IBaicgvOmmoILu5eI80AIiDbx02boSO4hx7voxNA5RB7GVupCjIYIpzPCKFLsPR/wzLeYzhGaPjldmScTlJWa42Ab3D6VFjh/91vBBvDJzEUy6dSjOH0faJEgPYPjFhkun/j+rlpJSz6MpLUC+jKBB/Cj+kM9GrTx34p6XUpQes2X/WCTGxk9OFHCrHlitrXrz00MNKxYXjp8Igncqf97ttD96rt0W0kv88JHYMT/cg36Jf0tPa0TUNUg8Ff/jwLBEDgkKMa1vb4GFrBACkHHcqMuYz/UF7mc+pbR+/p5EYGpj2rznIi+fiOBIk5vV5UMi2oW5cWJyxQoeVM40CmB6GJ6eKH4/GPxbkN745NUsK5DJdNXqEGj6PTPTUlj3zqDikb/Rhovti/zhelQs8K2LCwwRDKjaB4RMZzE180tT2lvGD1EIXVunNPqJ1sHO/T0SivkTX3GBFsZobMIrmabdiU/RsAPnYm6DWrNeNyIuFn5vXmzBVPiaclUZ4iYvZRGqEBsuMe8TBviOE=
